{
 "title": "Greenhouse #204",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Greenhouse Air Temperature #204",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Greenhouse Air Temperature",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "devices",
     "query": "SELECT mean(temperature) FROM devices WHERE (id = 204) AND $timeFilter GROUP BY time(5m) fill(linear)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=", "value": "187" }
     ]
    }
   ]
  },
  {
   "title": "Max temp #204",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Greenhouse Soil Humidity",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "devices",
     "query": "SELECT max(\"temperature\") FROM \"devices\" WHERE (\"id\" = 204) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg temp #204",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 1, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Greenhouse Soil Humidity",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "devices",
     "query": "SELECT mean(\"temperature\") FROM \"devices\" WHERE (\"id\" = 204) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Greenhouse Soil Moisture #204",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "alias": "Greenhouse Air Humidity",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "devices",
     "query": "SELECT mean(\"humidity\") FROM \"devices\" WHERE (\"id\" = 204) AND $timeFilter GROUP BY time(5m) fill(linear)",
     "select": [
      [
       { "params": [ "soilmoisture" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Soil Moisture #204",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Greenhouse Soil Humidity",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "devices",
     "query": "SELECT max(\"soilmoisture\") FROM \"devices\" WHERE $timeFilter GROUP BY time(5m) fill(linear)",
     "select": [
      [
       { "params": [ "soilmoisture" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg luminosity #204",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 1, "x": 23, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Greenhouse Soil Humidity",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "devices",
     "query": "SELECT mean(\"luminosity\") FROM \"devices\" WHERE (\"id\" = 204) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "luminosity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Min temp #204",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Greenhouse Soil Humidity",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "devices",
     "query": "SELECT min(temperature) FROM devices WHERE (id = 204) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Min Soil Moisture #204",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Greenhouse Soil Humidity",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "devices",
     "query": "SELECT min(\"soilmoisture\") FROM \"devices\" WHERE $timeFilter GROUP BY time(5m) fill(linear)",
     "select": [
      [
       { "params": [ "soilmoisture" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Greenhouse Air Humidity #204",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "alias": "Greenhouse Air Humidity",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "devices",
     "query": "SELECT mean(\"humidity\") FROM \"devices\" WHERE (\"id\" = 204) AND $timeFilter GROUP BY time(5m) fill(linear)",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max humd_air #204",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Greenhouse Soil Humidity",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "devices",
     "query": "SELECT max(\"humidity\") FROM \"devices\" WHERE (\"id\" = 204) AND $timeFilter GROUP BY time(5m) fill(linear)",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=", "value": "204" }
     ]
    }
   ]
  },
  {
   "title": "Avg luminosity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 1, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Greenhouse Soil Humidity",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "devices",
     "query": "SELECT mean(\"luminosity\") FROM \"devices\" WHERE (\"id\" = 204) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Greenhouse Luminosity #204",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Greenhouse Luminosity",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "devices",
     "query": "SELECT mean(\"luminosity\") FROM \"devices\" WHERE (\"id\" = 204) AND $timeFilter GROUP BY time(5m) fill(linear)",
     "select": [
      [
       { "params": [ "luminosity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max luminosity #204",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Greenhouse Soil Humidity",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "devices",
     "query": "SELECT max(\"luminosity\") FROM \"devices\" WHERE (\"id\" = 204) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "luminosity" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg luminosity #204",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 1, "x": 23, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Greenhouse Soil Humidity",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "devices",
     "query": "SELECT mean(\"luminosity\") FROM \"devices\" WHERE (\"id\" = 204) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "luminosity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Min humd_air #204",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Greenhouse Soil Humidity",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "devices",
     "query": "SELECT min(\"humidity\") FROM \"devices\" WHERE (\"id\" = 204) AND $timeFilter GROUP BY time(5m) fill(linear)",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=", "value": "204" }
     ]
    }
   ]
  },
  {
   "title": "Min luminosity #204",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 21, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Greenhouse Soil Humidity",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "devices",
     "query": "SELECT min(\"luminosity\") FROM \"devices\" WHERE (\"id\" = 204) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "luminosity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}